### PR TITLE
Added support for passing a 'compare' function used to sort

### PR DESCRIPTION
**Pull request by xaeroseven**
We've been using Semantic UI's Table component and your sort plugin but we needed alpha numeric sorting like what Dave Koelle outlined on his website here: http://www.davekoelle.com/alphanum.html.  With this changeset we can provide Dave's alpha-numeric sorting or any other custom compare function to your plugin.

Hope it helps 👍

### CODE REVIEW

**Comment by kylefox** [comment]
Cool idea, thanks for submitting this! Would you mind adding some basic documentation to the README? Then I'll be happy to merge & cut a new release 👍

**Comment by kylefox** [comment]
Actually, I'll do it now so I can release a couple fixes as well. Thanks again!

**Comment by kylefox** [comment]
This is now available in [v0.0.11](https://github.com/kylefox/jquery-tablesort/tree/v0.0.11).

**Comment by xaeroseven** [comment]
So sorry, just noticed that I didn't have my notifications turned on for participating threads in github.  Glad you got it merged and released, happy to help 👍

**Pull request merged**
